name: Release Pipeline

on:
  push:
    branches:
      - main   # Ce workflow sera déclenché lorsque tu pousses sur la branche 'main'

jobs:
  release:
    runs-on: ubuntu-latest   # Choisir l'environnement d'exécution (ici un serveur Ubuntu)

    permissions:
      contents: write  # Autoriser les actions de lecture et écriture sur les contenus du dépôt
      id-token: write  # Nécessaire pour les actions de push avec GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Cloner ton dépôt

      - name: Configure Git user
        run: |
          git config --global user.email "hicham.makhlouf@ynov.com"
          git config --global user.name "HichOps"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'   # Version de Node.js à utiliser, modifie selon ton projet

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npx jest --detectOpenHandles  # Exécuter les tests

      - name: Set executable permissions for release.sh
        run: chmod +x ./release.sh

      - name: Execute release script
        run: |
          ./release.sh standard-version  # Utilise l'outil de ton choix dans le script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour pousser les tags et créer une release GitHub

      - name: Push changes
        run: |
          git push --follow-tags origin main  # Pousser les modifications et les tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
